### ISSUE TITLE
Duplicated parse_url

### ISSUE THREAD

**Issue by pionl** [JustSteveKing/uri-builder#4]
Hi @JustSteveKing,

what is the reason that you are parsing fragment with [parse_url($original)](https://github.com/JustSteveKing/uri-builder/blob/9fe2234ae4071ad0a6dd1ea96365e7b9f2024bc8/src/Uri.php#L92) and not using already parsed [uri](https://github.com/JustSteveKing/uri-builder/blob/9fe2234ae4071ad0a6dd1ea96365e7b9f2024bc8/src/Uri.php#L56) on start?

Thank you :)

**Comment by JustSteveKing** [comment]
So adding the filter to get just the fragment needs to be called separately to make sure you fetch any potential fragments, the parse_url by default will ignore this unless specified.

**Comment by pionl** [comment]
Thanks for the info
